#ALL.mk
#	Created on: Jan 11, 2020
#		Author: badquanta
# just collections that will be used by GOALS.mk
### these will be used by the makefile to generate global/common rules.
ALL_SUFFIXES +=
ALL_INCLUDES +=
ALL_DEFAULTS +=
ALL_PHONY	 +=
## Dep files generated by GCC; stored in build directory and only referenced on rebuilds.
ALL_DEP_FILES				+=
ALL_OBJS	 				+=
ALL_CLEAN					+=
ALL_MOSTLYCLEAN				+=
ALL_MAINTAINER_CLEAN		+=
ALL_DIST_CLEAN				+=
ALL_REAL_CLEAN				+=
ALL_CLOBBER					+=
ALL_INSTALL					+=