# BQos COMMON.mk
# defines project-wide defaults and MACROS
#
# DIRS.mk will pull in CONFIG.mk as well; where we'll get the values for
# the below defaults
include MAKE/dirs.conf.mk
# This file is one that is generated by the `configure` script in the root
# of this repo.  It is executable and if run will re-`configure` the repo
# just as was originally done with the `configure` script.  
CONFIG_STATUS := config.status

CFLAGS := \
	-Iinclude \
	-Iinclude/libc \
	-fno-omit-frame-pointer \
	-Wall \
	-static \
	-Wextra \
	-pedantic \
	-Wshadow \
	-Wpointer-arith \
	-Wcast-align \
	-Wwrite-strings \
	-Wmissing-declarations \
	-Wredundant-decls \
	-Winline \
	-Wno-long-long \
	-Wconversion \
	-Wno-write-strings \
	-MD
CXXFLAGS := $(CFLAGS)
# TODO: Do we need GAS flags?
PROJECT_GASFLAGS +=	
################################################################### MACROS
# Some macros used for debugging/output/status.
UPDATE_STATUS 	= mkdir -p "./logs/$(@D)"; $(STATUSVG) "$@"
#REDIRECT :=  >> $(PREFIX)/build.log 2>&1
GIT_SHALLOW		= git clone --depth 1 --single-branch --branch
CLEAN			= - rm -frv
REACHED 		= @ mkdir -p $(TARGETS);  date >>  
STATUS			= @./scripts/status.sh 
STATUSVG		= ./scripts/make-target-graph.sh 
export function if_e { if [ -e $1 ]; then $2 $1; else echo "$1 does not exist."; fi; }
## ^ OR v  ##
#REDIRECT := 2>&1 | tee --output-error=warn -a